// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TucGolfklubb.Data;

#nullable disable

namespace TucGolfklubb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250413091447_AddForumReplyIdToUserActivity")]
    partial class AddForumReplyIdToUserActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "TucUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "TucUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "TucUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "TucUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "TucUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "TucUserMngt");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivityViewedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "TucUserMngt");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Klubbor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kläder"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Skor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Väskor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tillbehör"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bollar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Träningsutrustning"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elektronik"
                        });
                });

            modelBuilder.Entity("TucGolfklubb.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Forums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Diskussioner om allt möjligt relaterat till golf",
                            Title = "Allmänt om golf"
                        });
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Välkommen till forumet! Vad tycker ni om den nya golfbanan?",
                            ForumId = 1,
                            PostedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForumPostId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentReplyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ForumPostId");

                    b.HasIndex("ParentReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TucGolfklubb.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "En kraftfull driver med låg spinn och stor sweetspot som förlåter snedträffar. Den aerodynamiska formen ger dig extra fart i svingen utan att du behöver ta i för kung och fosterland. Justerbart loft gör det enkelt att finjustera till just din sving.",
                            Image = "shop-klubbor.jpg",
                            Name = "Driver – PowerDrive X",
                            Price = 2999.00m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cavity-back-designen ger dig en bra kombination av kontroll och förlåtelse. Lång järn? Distans. Kort järn? Precision. Det är klubbor som växer med dig – oavsett om du är stabil 15 i handicap eller på väg ner mot singel.",
                            Image = "shop-klubbor.jpg",
                            Name = "Järnklubba – Precision 7",
                            Price = 1299.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Den frästa träffytan ger maximalt grepp och kontroll på korta slag. SpinMaster Pro är din bästa vän från bunkern, ruffen eller fairway 80 meter in. Med flera loft att välja mellan kan du bygga ett närspel som passar just ditt spel.",
                            Image = "shop-klubbor.jpg",
                            Name = "Wedge – SpinMaster Pro",
                            Price = 1199.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Klassisk bladputter med face-milled träffyta för mjuk bollstart och jämnt rull. Den är lätt att rikta, ger stabil feedback och hjälper dig hålla nerverna i schack på de där svettiga parputtarna. En favorit bland både traditionsälskare och resultatinriktade golfare.",
                            Image = "shop-klubbor.jpg",
                            Name = "Putter – TrueRoll Classic",
                            Price = 1499.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Den här mjuka fleecetröjan är framtagen för att ge dig full rörelsefrihet i svingen, samtidigt som den håller dig varm. Perfekt lager att ha under jackan eller över en piké. Diskret klubbmärke på ärmen för en snygg och stilren look.",
                            Image = "shop-kläder.jpg",
                            Name = "Tröja - Fairway Fleece",
                            Price = 499.00m,
                            Stock = 23
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Våra golfbyxor är tillverkade i ett följsamt, stretchigt material som anpassar sig efter ditt spel. Lika sköna att bära som de ser bra ut. Andas väl under varma dagar och har en ren, klassisk look. Självklart med subtil klubbbranding – för dig som spelar med stil.",
                            Image = "shop-kläder.jpg",
                            Name = "Byxor - Greenline Flex",
                            Price = 649.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Vår klassiska klubbjacka är perfekt för kyliga morgonrundor eller blåsiga eftermiddagar. Lätt, vindtät och vattenavvisande – samtidigt som den andas. Med klubbens broderade logotyp på bröstet visar du stolt var du hör hemma. Passar lika bra på banan som på uteserveringen efter 18 hål.",
                            Image = "shop-kläder.jpg",
                            Name = "Jacka - Windbreaker Classic",
                            Price = 699.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "En keps är inte bara praktisk – den är en del av looken. Vår Club Cap skyddar mot sol och ger ett skönt avslappnat intryck. Justerbar passform, slitstarkt tyg och broderad klubbemblem framtill. En självklarhet i varje golfbags utrustning.",
                            Image = "shop-kläder.jpg",
                            Name = "Keps - Club Cap",
                            Price = 249.00m,
                            Stock = 42
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "GripTech Tour ger dig stabilitet i varje sving tack vare sina utbytbara softspikes. Skon är vattentät men andas, vilket gör den perfekt för heldagar på banan i alla väder. Ett måste för dig som prioriterar fäste, särskilt på blöta eller kuperade banor.",
                            Image = "shop-skor.jpg",
                            Name = "Spikade skor – GripTech Tour",
                            Price = 1299.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "FlexWalk Pro är en stilren spikfri golfsko som funkar lika bra på banan som i klubbhuset. Greppig undersula i gummi ger stabilitet utan att du känner dig stel i steget. En favorit bland golfare som vill ha funktion och stil i ett.",
                            Image = "shop-skor.jpg",
                            Name = "Spikfria skor – FlexWalk Pro",
                            Price = 1099.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Med extra dämpning i häl och framfot ger ComfortDrive Max överlägsen komfort hela rundan. Mjuk innestruktur och stötdämpande sula minskar tröttheten i fötterna rejält. Idealisk för dig som går mycket på banan.",
                            Image = "shop-skor.jpg",
                            Name = "Dämpade skor – ComfortDrive Max",
                            Price = 1199.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Stadig och rymlig vagnväska med 14-delad topp och gott om smarta fack. ProTour 14 är perfekt för dig som spelar med vagn eller elvagn och vill ha full översikt. Vattentåliga fickor och integrerat regnskydd ingår.",
                            Image = "shop-väskor.jpg",
                            Name = "Caddyväska – ProTour 14",
                            Price = 2199.00m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "CarryLite 6 är en praktisk bärbag med dubbelbärsele, lättviktsmaterial och stabila ben. Trots sin lätta vikt får du plats med klubbor, kläder och tillbehör för en hel runda. Perfekt för snabbrundor och sommarspel.",
                            Image = "shop-väskor.jpg",
                            Name = "Bärväska – CarryLite 6",
                            Price = 1499.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Miljövänliga trätees i klassisk modell – hållbara, snygga och skonsamma mot miljön. Kommer i 50-pack så att du klarar dig över många rundor. Finns i flera längder.",
                            Image = "shop-tillbehör.jpg",
                            Name = "Tee – EcoTee 50-pack",
                            Price = 69.00m,
                            Stock = 71
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "GripFit-handsken är tillverkad i mjukt cabrettaläder för maximal känsla mot greppet. Den sitter tajt men ventilerar väl, även under varma rundor. En favorit bland både singelhandicapare och nybörjare.",
                            Image = "shop-tillbehör.jpg",
                            Name = "Handskar – GripFit Tour Glove",
                            Price = 179.00m,
                            Stock = 16
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "StormShield XL är ett stort, dubbelventilerat paraply som står emot vind och regn. Bekvämt handtag och snabböppning gör det lätt att använda även med en hand. Passar i de flesta vagnhållare.",
                            Image = "shop-tillbehör.jpg",
                            Name = "Paraply – StormShield XL",
                            Price = 349.00m,
                            Stock = 37
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Mjuk men slitstark mikrofiberhandduk med klubbens logga. Lätt att fästa med karbinhake och torkar snabbt efter rengöring. En självklarhet i varje bag.",
                            Image = "shop-tillbehör.jpg",
                            Name = "Handduk – ClubTowel Pro",
                            Price = 129.00m,
                            Stock = 33
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "Tourklassad boll med mjuk kärna och hög spinnkontroll runt green. Passar både låg- och medelhandicapare som vill ha det bästa av två världar. Säljs i 12-pack.",
                            Image = "shop-bollar.jpg",
                            Name = "Bollar – SoftSpin Tour 12-pack",
                            Price = 289.00m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Description = "En slitstark, hoprullbar puttingmatta med markerade avstånd och hål. Perfekt för träning hemma eller på kontoret. Ger en jämn och realistisk rull för bättre känsla.",
                            Image = "shop-träningsutrustning.jpg",
                            Name = "Puttingmatta – HomeGreen Roll-Up",
                            Price = 699.00m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "SwingTrainer Pro hjälper dig bygga upp rytm, timing och styrka i svingen. Fungerar både som uppvärmning före runda och träning hemma. Lätt att använda, men svår att släppa.",
                            Image = "shop-träningsutrustning.jpg",
                            Name = "Träningsredskap – SwingTrainer Pro",
                            Price = 499.00m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            Description = "GolfNav Mini är en smidig GPS-klocka med tusentals banor förladdade. Visar avstånd till greenens framkant, mitten och bakkant, samt hinder. Batteritid för flera rundor.",
                            Image = "shop-elektronik.jpg",
                            Name = "GPS-enhet – GolfNav Mini",
                            Price = 1499.00m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Description = "Snabb och exakt avståndsmätare med flaggsökning och vibrationsfeedback. Räckvidd upp till 600 meter och tydlig display. Kommer med skyddsfodral och batteri.",
                            Image = "shop-elektronik.jpg",
                            Name = "Avståndsmätare – PinPoint Laser 600",
                            Price = 1799.00m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Description = "ShotSync är en smart sensorsnäppa som fästs på klubban och analyserar din sving i realtid. Kopplas till app där du kan se tempo, plan och vinkel. Perfekt för tekniknörden som vill utvecklas på riktigt.",
                            Image = "shop-elektronik.jpg",
                            Name = "Extra elektronik – ShotSync SwingSensor",
                            Price = 1099.00m,
                            Stock = 3
                        });
                });

            modelBuilder.Entity("TucGolfklubb.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("TucGolfklubb.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ForumPostId")
                        .HasColumnType("int");

                    b.Property<int?>("ForumReplyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TucGolfklubb.Models.UserFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FolloweeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TucGolfklubb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TucGolfklubb.Models.Booking", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Forum", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumPost", b =>
                {
                    b.HasOne("TucGolfklubb.Models.Forum", "Forum")
                        .WithMany("Posts")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumReply", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ForumPost", "ForumPost")
                        .WithMany("Replies")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TucGolfklubb.Models.ForumReply", "ParentReply")
                        .WithMany("ChildReplies")
                        .HasForeignKey("ParentReplyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ForumPost");

                    b.Navigation("ParentReply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Order", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.OrderItem", b =>
                {
                    b.HasOne("TucGolfklubb.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TucGolfklubb.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TucGolfklubb.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("OrderItems")
                        .HasForeignKey("ShoppingCartId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Product", b =>
                {
                    b.HasOne("TucGolfklubb.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Review", b =>
                {
                    b.HasOne("TucGolfklubb.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.UserActivity", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TucGolfklubb.Models.UserFollow", b =>
                {
                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TucGolfklubb.Models.ApplicationUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ApplicationUser", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Forum", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumPost", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ForumReply", b =>
                {
                    b.Navigation("ChildReplies");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TucGolfklubb.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TucGolfklubb.Models.ShoppingCart", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
